### ISSUE TITLE
[question] Is otter.nvim a plugin of choice just to implement syntax highlighting

### ISSUE THREAD

**Issue by eshepelyuk** [jmbuhr/otter.nvim#249]
Hello

My use case is YAML files that could have embedded languages inside nodes, smth like

```yaml
steps:
  - script:
      groovy: | 
        println "Hello groovy world @ ${System.currentTimeMIllis()}"
  - script:
      python: |
        from datetime import datetime
        print(f"Hello python world @ {datetime.now()}")
```

1. is it possible to leverage otter.nvim to detect languages inside non markdown files ?
1. if yes, is it a good choice to use this plugin if I only want syntax highlighting ?
